### ISSUE TITLE
Add Zoom In and Zoom Out option for the documents

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#22]
This issue was originally raised via forum thread:
https://forum.groupdocs.com/t/multipage-tiff-not-working/6882/7

A new feature is requested. Please add Zoom In and Zoom Out feature for the documents. Thanks

**Comment by Pavel-Teplitsky** [comment]
Hi @samicheemagroupdocs , we will add it to our road map.

**Comment by egorovpavel** [comment]
This is GroupDocs.Viewer feature and it is not supported in GroupDocs.Annotation.
We are not planning on implementing it in near feature.
All GroupDocs.Annotation available features can be found at `configuration.yml`.

Please note that we've updated our sample and removed all non GroupDocs.Annotation related parameters from `Index.cshtml` in order to avoid any further confusion.

**Comment by egorovpavel** [comment]
@samicheemagroupdocs  this feature has been released. Please pull the latest version, rebuild project and clean browser cache.
