### ISSUE TITLE
Show Thumbnails of the selected document

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#24]
This issue was originally raised via forum thread:
https://forum.groupdocs.com/t/multipage-tiff-not-working/6882/7

A new feature is requested. Please show Thumbnails of the selected document. For further reference, please see the highlighted part of attached screenshot. Thanks

![thumbnails](https://user-images.githubusercontent.com/29034002/50588173-b6732100-0ea2-11e9-849e-c1f4f3999248.PNG)

**Comment by egorovpavel** [comment]
Currently, this feature is not supported in this sample. Thumbnail functionality requires server-side support which is only provided by GroupDocs.Viewer.
So this feature is only supported within GroupDocs.Viewer.

Please note that we've updated our sample and removed all non GroupDocs.Annotation related parameters from `Index.cshtml` in order to avoid any further confusion.
All GroupDocs.Annotation available features can be found at `configuration.yml`.
