### ISSUE TITLE
Unable to build the project in sub directory

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#4]
This issue was originally raised via forum thread: This issue was originally raised via forum thread: https://forum.groupdocs.com/t/need-javascript-version-for-document-annotation/6138/24

Hi,

While trying to build the project in a single sub directory, following errors were thrown:

* Cannot find module 'npmlog'	GroupDocs.Annotation.MVC
* NuGet Package restore failed for project GroupDocs.Annotation.MVC: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters..
* The command "..\packages\NodeBin.5.2.0\node-5.2.0\node.exe ..\packages\NodeBin.5.2.0\npm-2.14.13\bin\npm-cli.js install" exited with code 1

Please see the below screenshot for further reference. Thanks

![image](https://user-images.githubusercontent.com/29034002/47635587-55b02b00-db77-11e8-8a6e-fd63ce3f3c0c.png)

**Comment by Pavel-Teplitsky** [comment]
Hi Sami, 

This issue is not related to the example itself, this is system restrictions of the Windows OS, for more info about it you can check official Microsoft documentation . Also if you will take a look at this discussion you will find out that the Nuget doesn’t support file paths longer than 260 characters as well - only for Win10 but not completely. 
Since that I can suggest next: use a shorter path to store example, something like this c:\GroupDocs

Best regards
