### ISSUE TITLE
Can we hide selected Annotation type when save button is pressed? 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#71]
This issue is raised in https://forum.groupdocs.com/t/selected-annotation-type-hide-when-save-button-press/9605

Hi,
Is there a way to hide the selected annotation type when we/user press the save button? User wants to hide the selected annotation type options when saving the document.
Have a look at the attached screencast.
[hideannotation.zip](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC/files/6357461/hideannotation.zip)

**Comment by bobkovalex** [comment]
Hi @atirtahirgroupdocs 

At the moment there is no way to hide annotations. And I suggest to not remove them like in the screencast you've shared, because removed annotations will be deleted upon document saving.
UI annotations are used for annotation editing, even after you have saved document you still able to edit your previous annotations.

Anyway, we will add an improvements which will have a show/hide UI annotation toggle button.

Regards,
Alex

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

We've implemented show/hide UI annotations toggle button.
Just rebuild GroupDocs.Annotation MVC project.
![115723309-85c39800-a388-11eb-8b8c-fbd914910c34](https://user-images.githubusercontent.com/2103709/115746308-e8269380-a39c-11eb-87ca-44bad49d7781.png)

Regards,
Alex

**Comment by ImSMRizwan** [comment]
@bobkovalex,  I checked and rebuild the project, but no changes effected.

![image](https://user-images.githubusercontent.com/17806022/115923262-68312400-a497-11eb-84df-e672171557ae.png)

**Comment by kegor** [comment]
Hi @ImSMRizwan,

Could you please try following steps:
1. Remove file `GroupDocs.Annotation-for-.NET-MVC/src/client/package-lock.json`
2. Remove folder `GroupDocs.Annotation-for-.NET-MVC/src/client/node_modules/@groupdocs.examples.angular`
3. Rebuild and run solution.
4. Refresh app in browser using Ctrl+F5.

Thank you,
Egor.
